### ISSUE TITLE
[BUG] Improve Documentation

### ISSUE THREAD

**Issue by manishraj27** [gdsc-klef/DSA-Projects#1]
**Describe the bug**

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- OS: [e.g. Windows, MacOS]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by karshav16** [comment]
Would like to work on this issue as my at most favorite and priority. Kindly Assign!

**Comment by manishraj27** [comment]
Go ahead!
Make sure you stick to the guidelines!

**Comment by karshav16** [comment]
Would kindly request you to assist this issue to me.

**Comment by karshav16** [comment]
Would kindly request you to assign this issue to me!
