### ISSUE TITLE
[FEATURE] Implement BinarySearch.java

### ISSUE THREAD

**Issue by manishraj27** [gdsc-klef/DSA-Projects#2]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex: I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by karshav16** [comment]
Would like to get assigned can add a implementation of binary search in java with worst time complexity less than o(logn) kindly assign!

**Comment by manishraj27** [comment]
Go Ahead!

**Comment by karshav16** [comment]
Sure, Would get back to you with a pull request soon!

**Comment by karshav16** [comment]
I have completed the task and attached the most efficient way and have also documented it in start. Kindly Accept!
